plugins { id 'com.android.application' }

android {
    namespace 'pl.zabka.wyczysctms'
    compileSdk 35

    defaultConfig {
        applicationId 'pl.zabka.wyczysctms'
        minSdk 23
        targetSdk 35
        versionCode 9
        versionName '6.3-pin1010-modern'
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
